// Display page for single branch and edit
import React from 'react';
import Head from 'next/head';
import styles from '../../../styles/Home.module.css';
import Header from '../../../components/header';
import EditTaskView from '../../../components/editTaskView';
import Footer from '../../../components/footer';
import { ListGroup, ListGroupItem } from 'reactstrap';
import { getNode } from '../../../api/node';
import { getLine } from '../../../api/line';
import {connect} from 'react-redux';
import { withRouter } from 'next/router'
import Router from 'next/router';

class Home extends React.Component{
  constructor(props) {
    super(props);

    this.state = {task: [], line: []}

    this.getData = this.getData.bind(this)
    this.checkLogin = this.checkLogin.bind(this)
  }

  componentDidMount() {
    this.getData();
  }

  render() {
    let children = (
      <ListGroupItem className='empty d-flex justify-content-center align-items-center'>
        <div></div>
      </ListGroupItem>
    );
    if (this.state.task.length) {
      console.log(this.state.task)
      children = this.state.task.map((p) => (
        <ListGroupItem key={p._id} action>
          <EditTaskView {...p} line={this.state.line[0]} />
        </ListGroupItem>
      ));
    }
  
    return (
      <div className={styles.container}>
        <Head>
          <title>Edit Task</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
  
        <Header></Header>
  
        <main className={styles.main + ' bg-gray-100'}>
          <ListGroup>
              {children}
          </ListGroup>
        </main>
  
        <Footer></Footer>
      </div>
    );
  }

  checkLogin(){
    if(this.props.userId == -1){
      Router.push({
        pathname: '/login',
        query: {},
      }, `/login`);
    }
  }

  getData(){
    getNode(this.props.router.query.taskId).then( node => {
      getLine(node.mother_line_id).then (Line => {
        this.setState({task: [node], line: [Line]})
      })
    })
  }
}

const mapStateToProps = state => ({
  userId: state.login.userId
});

const mapDispatchToProps = {

};

export default connect(mapStateToProps, mapDispatchToProps)(withRouter(Home));